modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="wipeout"
version="0.0.2"
displayName="Wipeout"
displayURL="N/A" # URL HERE
credits="Ordalca" # Your name here
authors="Ordalca" # Your name here
description='''
Causes the player to teleport to a healer/bed on whiting out
'''

[[dependencies.wipeout]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wipeout]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"


[[dependencies.wipeout]]
    modId="pixelmon"
    mandatory=true
    versionRange="[9.1.6,)"
    ordering="NONE"
    side="BOTH"